<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>QC_FIREBASE_ANALYTICS;QC_GOOGLE_REWARDED;UNITY_ANDROID</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../QuietCamp/Assets/QuietCamp/OptionalSdk/*.cs" />
    <Compile Include="../../QuietCamp/Assets/QuietCamp/Scripts/Application/AdService.cs" />
  </ItemGroup>
</Project>
