using System;
using System.Collections.Generic;
using UnityEngine;
namespace QuietCamp.Infrastructure
{
    /// <summary>
    /// assetId -> prefab/footprint lookup generated by MvpContentBuilder.
    /// Direct references only — no fuzzy file search at runtime.
    /// </summary>
    public sealed class AssetCatalog : ScriptableObject
    {
        public const string ResourcePath = "QuietCamp/AssetCatalog";

        [Serializable]
        public sealed class Entry
        {
            public string assetId;
            public GameObject prefab;
            public string logicalFootprint;
            public string role;
            public int visualYaw;
        }

        [SerializeField] Entry[] _entries = new Entry[0];
        Dictionary<string, Entry> _map;

        public IReadOnlyList<Entry> Entries => _entries;

        public static AssetCatalog Load()
            => Resources.Load<AssetCatalog>(ResourcePath);

        void OnEnable() => _map = null;

        Dictionary<string, Entry> Map
        {
            get
            {
                if (_map == null)
                {
                    _map = new Dictionary<string, Entry>(StringComparer.Ordinal);
                    foreach (var e in _entries)
                        if (e != null && !string.IsNullOrEmpty(e.assetId))
                            _map[e.assetId] = e;
                }
                return _map;
            }
        }

        public bool TryGet(string assetId, out Entry entry)
            => Map.TryGetValue(assetId ?? string.Empty, out entry);

        public GameObject Prefab(string assetId)
            => TryGetValue(assetId, out var e) ? e.prefab : null;

        bool TryGetValue(string assetId, out Entry e) => Map.TryGetValue(assetId ?? string.Empty, out e);
    }
}
