// Read-only source audit. Run with Node from any working directory.
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'../../QuietCamp');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'Assets/QuietCamp/Resources/QuietCamp/audio_catalog.json'),'utf8'));
const yaml=fs.readFileSync(path.join(root,'Assets/QuietCamp/Resources/QuietCamp/AudioCatalog.asset'),'utf8');
const defs=[...yaml.matchAll(/^  - Key: (.+)\r?\n([\s\S]*?)(?=^  - Key: |^  _[a-zA-Z]|$(?![\s\S]))/gm)].map(m=>{
 const field=n=>{const v=m[2].match(new RegExp('^    '+n+': ([^\\r\\n]*)','m'));return v?v[1]:null;};
 return {key:m[1].trim(),guid:(m[2].match(/Clip:.*guid: ([a-f0-9]+)/)||[])[1],volume:Number(field('Volume')),spatialBlend:Number(field('SpatialBlend')),loop:field('Loop')==='1',maxSimultaneous:Number(field('MaxSimultaneous'))};
});
const list=cp.execFileSync('rg',['--files','Assets','-g','*.wav','-g','*.ogg','-g','*.mp3'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/).map(p=>p.replace(/\\/g,'/')).sort();
const round=(v,n=4)=>Number(v.toFixed(n)),db=v=>v>0?round(20*Math.log10(v),2):null;
function wav(b){
 if(b.toString('ascii',0,4)!=='RIFF'||b.toString('ascii',8,12)!=='WAVE')throw Error('Unsupported RIFF');
 let fmt,data;for(let i=12;i+8<=b.length;){const size=b.readUInt32LE(i+4),end=i+8+size;if(end>b.length)throw Error('Truncated RIFF');const id=b.toString('ascii',i,i+4);if(id==='fmt ')fmt=b.subarray(i+8,end);if(id==='data')data=b.subarray(i+8,end);i=end+(size&1);}
 if(!fmt||!data)throw Error('Missing fmt/data');let format=fmt.readUInt16LE(0);const channels=fmt.readUInt16LE(2),sampleRate=fmt.readUInt32LE(4),block=fmt.readUInt16LE(12),bits=fmt.readUInt16LE(14);if(format===65534&&fmt.length>=40)format=fmt.readUInt16LE(24);
 if(![1,3].includes(format))throw Error('Unsupported WAV encoding '+format);
 const bytes=bits/8,frames=Math.floor(data.length/block);let sum=0,dc=0,peak=0,clipped=0,first=[],last=[],earlySq=0,lateSq=0;const window=Math.min(frames,Math.round(sampleRate*.02));
 for(let f=0;f<frames;f++)for(let c=0;c<channels;c++){const o=f*block+c*bytes;let v;if(format===3)v=bits===32?data.readFloatLE(o):data.readDoubleLE(o);else if(bits===8)v=(data[o]-128)/128;else if(bits===16)v=data.readInt16LE(o)/32768;else if(bits===24)v=data.readIntLE(o,3)/8388608;else if(bits===32)v=data.readInt32LE(o)/2147483648;else throw Error('Unsupported bit depth');if(!Number.isFinite(v))throw Error('Nonfinite PCM');sum+=v*v;dc+=v;peak=Math.max(peak,Math.abs(v));if(Math.abs(v)>=.999)clipped++;if(f===0)first[c]=v;if(f===frames-1)last[c]=v;if(f<window)earlySq+=v*v;if(f>=frames-window)lateSq+=v*v;}
 return {durationSeconds:round(frames/sampleRate),channels,sampleRate,bits,format,decodedPcmBytes:frames*block,peakDbFS:db(peak),rmsDbFS:db(Math.sqrt(sum/(frames*channels))),dcOffset:round(dc/(frames*channels),7),samplesAtOrAbove0999:clipped,seamMaxAbs:round(Math.max(...first.map((v,c)=>Math.abs(last[c]-v))),6),first20msRmsDbFS:db(Math.sqrt(earlySq/(window*channels))),last20msRmsDbFS:db(Math.sqrt(lateSq/(window*channels)))};
}
const rows=list.map(assetPath=>{const file=path.join(root,assetPath),b=fs.readFileSync(file),meta=fs.existsSync(file+'.meta')?fs.readFileSync(file+'.meta','utf8'):'';const guid=(meta.match(/^guid: (\w+)/m)||[])[1],active=defs.find(x=>x.guid===guid),declared=manifest.sounds.find(x=>x.assetPath===assetPath),sha256=crypto.createHash('sha256').update(b).digest('hex');let measurement=null,error=null;if(/\.wav$/i.test(file)){try{measurement=wav(b);}catch(e){error=e.message;}}return {key:active?.key||null,assetPath,fileBytes:b.length,sha256,manifestHashMatches:declared?sha256===declared.sha256:null,activeDefinition:active||null,measurement,measurementNote:measurement?'Raw PCM measurements, not LUFS or listening review':error||'OGG listed and auditionable; PCM not decoded by this script',importer:Object.fromEntries(['loadType','compressionFormat','forceToMono','preloadAudioData','loadInBackground'].map(k=>[k,(meta.match(new RegExp('^\\s*'+k+': (.+)','m'))||[])[1]??null])),licenseStatus:declared?.licenseStatus||(/Generated/.test(assetPath)?'Procedurally generated in project; generator provenance in QuietCampAudioExtras.cs':'KenneyUI package; consult included license before redistribution')};});
if(rows.filter(r=>r.activeDefinition).length!==defs.length)throw Error('Unresolved active clip GUID');
const result={date:'2026-09-30',scope:'All WAV/OGG/MP3 returned by rg --files Assets, respecting ignore rules; no Library/package-cache or embedded model audio',method:'WAV PCM scan, SHA256, serialized catalog and importer audit. No perceptual listening claim. Seam metric is endpoint difference, not proof of a seamless loop.',count:rows.length,activeCount:defs.length,rows};
fs.writeFileSync(path.join(__dirname,'audio-analysis.json'),JSON.stringify(result,null,2)+'\n');
const fmt=n=>n==null?'—':n;
const table=['# Вимірювання звуків','',result.method,'','| Ключ / резерв | Файл | с | Канали | Гц | Peak dBFS | RMS dBFS | Шов Δ |','|---|---|---:|---:|---:|---:|---:|---:|',...rows.map(r=>`| ${r.key||'Резерв Kenney'} | ${path.basename(r.assetPath)} | ${fmt(r.measurement?.durationSeconds)} | ${fmt(r.measurement?.channels)} | ${fmt(r.measurement?.sampleRate)} | ${fmt(r.measurement?.peakDbFS)} | ${fmt(r.measurement?.rmsDbFS)} | ${fmt(r.measurement?.seamMaxAbs)} |`)];fs.writeFileSync(path.join(__dirname,'AUDIO-MEASUREMENTS.md'),table.join('\n')+'\n');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fs.writeFileSync(path.join(__dirname,'audio-listening.html'),`<!doctype html><html lang="uk"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QuietCamp — звуки</title><style>body{font:16px system-ui;background:#152d30;color:#f0e6cf;max-width:1100px;margin:30px auto;padding:20px}a{color:#ffd296}article{padding:16px;background:#203c3c;margin:12px 0;border-radius:14px}audio{width:min(100%,450px)}small{display:block;overflow-wrap:anywhere;margin:8px 0;color:#b9cebb}h2{font-size:18px}</style><h1>Звукова палітра QuietCamp</h1><p>23 джерела: 17 активних і 6 резервних. Натисніть Play для прослуховування; одночасно грає один файл. Початкова гучність 20%. Це оригінальні записи без запропонованих 3D-ефектів.</p><p><a href="preview.html">До графіки</a> · <a href="02-AUDIO-PROMPT-UA.md">Карта дій і звуків</a></p>${rows.map(r=>`<article><h2>${esc(r.key||'Резерв Kenney — '+path.basename(r.assetPath))}</h2><small>${esc(r.assetPath)} · ${r.measurement?`${r.measurement.durationSeconds} с; ${r.measurement.channels} кан.; RMS ${r.measurement.rmsDbFS} dBFS`:'OGG — вимірювання PCM не виконано'}</small><audio controls preload="none" src="../../QuietCamp/${r.assetPath.split('/').map(encodeURIComponent).join('/')}"></audio></article>`).join('')}<script>const clips=[...document.querySelectorAll('audio')];clips.forEach(a=>{a.volume=.2;a.addEventListener('play',()=>clips.forEach(b=>{if(a!==b)b.pause()}))});</script></html>`);
console.log(JSON.stringify({files:rows.length,active:defs.length,wavMeasured:rows.filter(r=>r.measurement).length,hashMismatches:rows.filter(r=>r.manifestHashMatches===false).length,errors:rows.filter(r=>/Unsupported|Truncated|Missing/.test(r.measurementNote)).length}));
