#!/usr/bin/env python3
"""Derive fixed menu styles from the canonical CSS, preserving order and media rules.

Run after editing Camp.css.txt; --check rejects stale derived assets. The main menu
never acquires map/gameplay classes, so it need not parse their stylesheet rules.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / 'QuietCamp/Assets/QuietCamp/Resources/QuietCamp/Html'
MAIN = set('app top grow primary quiet orb brand brand-sprig brand-title tagline menu-top menu-actions menu-cards menu-card mc-main mc-hex hex_map hex_tent mc-text mc-title mc-sub mc-symbol mc-progress mc-progress-fill cta cta-symbol cta-text cta-title cta-sub ico ico-play ico-settings ico-map ico-tent guide-card menu-guide guide-portrait guide-copy guide-name guide-instruction guide-ok'.split())


def subset(css, classes):
    result = []
    cursor = 0
    while cursor < len(css):
        opening = css.find('{', cursor)
        if opening < 0:
            assert not css[cursor:].strip(), 'Unexpected trailing CSS'
            break
        selector = css[cursor:opening].strip()
        depth, end, quote = 1, opening + 1, None
        while depth:
            assert end < len(css), 'Unbalanced CSS'
            char = css[end]
            if quote:
                if char == quote and css[end-1] != '\\':
                    quote = None
            elif char in "\"'":
                quote = char
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
            end += 1
        body = css[opening+1:end-1]
        if selector.startswith('@media'):
            nested = subset(body, classes)
            if nested:
                result.append(selector + ' {\n' + nested + '}\n')
        elif selector.startswith('@'):
            assert selector.startswith('@font-face'), 'Extend generator for this CSS at-rule: ' + selector
            result.append(selector + ' {' + body + '}\n')
        else:
            selected = [part.strip() for part in selector.split(',')
                        if set(re.findall(r'\.([\w-]+)', part)) <= classes]
            if selected:
                result.append(', '.join(selected) + ' {' + body + '}\n')
        cursor = end
    return ''.join(result)


def main():
    check = argparse.ArgumentParser()
    check.add_argument('--check', action='store_true')
    args = check.parse_args()
    css = re.sub(r'/\*.*?\*/', '', (DIRECTORY/'Camp.css.txt').read_text(), flags=re.S)
    all_classes = set(re.findall(r'\.([\w-]+)', css))
    map_classes = {c for c in all_classes if c.startswith(('map-', 'roadmap', 'node-', 'branch-', 'bonus-', 'act-', 'ico'))}
    map_classes -= {c for c in map_classes if c.startswith(('bonus-preview', 'bonus-description', 'bonus-requirement', 'bonus-condition', 'bonus-count', 'bonus-progress'))}
    map_classes.update('app dimroot full-menu full-header full-title nav-back quiet hidden selected locked done veiled bonus-ready branch-ready person left right head body'.split())
    for name, classes in [('CampMain.css.txt', MAIN), ('CampBackdrop.css.txt', {'app', 'menu-atmosphere'}), ('CampMap.css.txt', map_classes)]:
        content = '/* Generated by tools/prepare_ui_styles.py; edit Camp.css.txt. */\n' + subset(css, classes)
        path = DIRECTORY/name
        if args.check:
            assert path.read_text() == content, 'Regenerate ' + name
        else:
            path.write_text(content)
        print(name, len(content.encode()), 'bytes')


if __name__ == '__main__':
    main()
